### ISSUE TITLE
Not an issue, but a thank you!

### ISSUE THREAD

**Issue by tmccdev** [d-Rickyy-b/GolangTour-Dark#1]
I didn't know there was a dark theme for the Golang tour page out there, and I feel silly for having not considered there would be one.

My eyesight has been saved, and for that, I thank you greatly :)

**Comment by d-Rickyy-b** [comment]
Thanks for your appreciation :) - my eyes were bleeding already, so I created this dark theme. Glad I can save other eyes from burning.
